version: '3.8'

services:
  reverse:
    container_name: reverse
    hostname: 192.168.1.112
    image: nginx:latest
    ports:
      - 8050:80
      - 443:443
    restart: always
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - umbrel_main_network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./var/www/certbot/:/var/www/certbot/
      - ./etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true